//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceReco
{
    using System;
    using System.Collections.Generic;
    
    public partial class stagiaireEncod
    {
        public int cef { get; set; }
        public string stringEncod { get; set; }
    
        public virtual Stagiaire Stagiaire { get; set; }
    }
}
