//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceReco
{
    using System;
    using System.Collections.Generic;
    
    public partial class presenceHistory
    {
        public int id { get; set; }
        public string cef { get; set; }
        public string idIntr { get; set; }
        public Nullable<System.DateTime> dateHistory { get; set; }
    
        public virtual Intruder Intruder { get; set; }
        public virtual Stagiaire Stagiaire { get; set; }
    }
}
